# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-20 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
