# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20170820_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='imageAdr',
            field=models.CharField(default='0', max_length=500),
            preserve_default=False,
        ),
    ]
