# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_auto_20170829_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.FileField(upload_to='./festival/userImages/', verbose_name='File'),
        ),
    ]
