# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-29 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_auto_20170829_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
    ]
