# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-29 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_remove_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='imageAdr',
        ),
    ]
