# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-02 16:11
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_remove_link_imageadr'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
