# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-02 16:26
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_main_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='color',
        ),
        migrations.AddField(
            model_name='main',
            name='Background_Color_Down',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='main',
            name='Background_Color_Navigation_Bar',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='main',
            name='Background_Color_Up',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='main',
            name='Background_Image_Down',
            field=models.FileField(default='', upload_to='./festival/userImages/', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='Background_Image_Up',
            field=models.FileField(default=' ', upload_to='./festival/userImages/', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='Font_Style_Navigation_Bar',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='Forground_Color_Navigation_Bar',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='main',
            name='Use_of_Image_Background_Down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main',
            name='Use_of_Image_Background_Up',
            field=models.BooleanField(default=False),
        ),
    ]
