# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0009_auto_20170902_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Font_Size_Navigation_Bar',
            field=models.IntegerField(default='22'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Font_Style_Navigation_Bar',
            field=models.TextField(default='Crimson Text'),
        ),
    ]
