# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0010_auto_20170902_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='Font_Style_Navigation_Bar',
            field=models.CharField(default='Crimson Text', max_length=50),
        ),
    ]
