# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-02 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0011_auto_20170902_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='Background_Color_Down',
            new_name='background_color_down',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Background_Color_Navigation_Bar',
            new_name='background_color_navigation_bar',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Background_Color_Up',
            new_name='background_color_up',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Background_Image_Down',
            new_name='background_image_down',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Background_Image_Up',
            new_name='background_image_up',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Font_Size_Navigation_Bar',
            new_name='font_size_navigation_bar',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Font_Style_Navigation_Bar',
            new_name='font_style_navigation_bar',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Forground_Color_Navigation_Bar',
            new_name='foreground_color_navigation_bar',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Use_of_Image_Background_Down',
            new_name='use_of_image_background_down',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='Use_of_Image_Background_Up',
            new_name='use_of_image_background_up',
        ),
    ]
