# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-02 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0012_auto_20170902_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='background_color_navigation_bar',
        ),
        migrations.RemoveField(
            model_name='main',
            name='foreground_color_navigation_bar',
        ),
    ]
