# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-02 17:46
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0013_auto_20170902_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='background_color_navigation_bar',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='main',
            name='foreground_color_navigation_bar',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
