# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-04 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0017_auto_20171104_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_to_show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festival.Main')),
            ],
        ),
    ]
